siemens/ix-blazor

SiemensIXBlazor/Components/Select/Select.razor.cs
Due to .NET internal transformation of the provided JSON array, it can happen that ValueChanged receives a JsonElement of type String instead of Array, resulting in an error then trying to deserialize it into an array. This commit fixes that.
=> Fix json deserialization error on select value changed

SiemensIXBlazor/Components/Button/IconButton.razor
While creating #23 , I forgot to convert the enum correctly to an integer. This got noted by #24 and should be fixed by this commit.
=> Fixed IconButton size error

SiemensIXBlazor/Components/AGGrid/AGGrid.razor.cs
`window.agGridInterop.createGrid` returns the actual JS instance of the AG-Grid. This change exposes the return to the .NET side.
=> Make AG-Grid JS instance accessible

SiemensIXBlazor/Components/AGGrid/ColumnDefs.cs, SiemensIXBlazor/Components/Breadcrumb/Breadcrumb.razor, SiemensIXBlazor/Components/EventList/EventList.razor, SiemensIXBlazor/Components/NavigationMenu/NavigationMenuCategory.razor, SiemensIXBlazor/Components/NavigationMenu/NavigationMenuCategory.razor.cs, SiemensIXBlazor/SiemensIXBlazor.csproj
- AGGrid column width properties
- Eventlist animated property tostring
- Breadcrumb ghost property tostring
- NavigationMenuCategory fix
=> Minor fixes, missing properties

SiemensIXBlazor.Tests/DrawerTests.cs, SiemensIXBlazor.Tests/TestContextBase.cs, SiemensIXBlazor/Components/Drawer/Drawer.razor.cs
GitHub Issue Number: #46 
Drawer test added with TestContextBase class
.
Please check SiemensIXBlazor/Components/Drawer/Drawer.razor.cs changes and TextContextBase functionality.
=> Drawer test added with TestContextBase class

SiemensIXBlazor.Tests/Dropdown/DropdownItemTest.cs, SiemensIXBlazor/Components/Dropdown/DropdownItem.razor, SiemensIXBlazor/Components/Dropdown/DropdownItem.razor.cs
Change dropdown item to return the component instead of just the label to better match the ix core library functionality
Currently, the Dropdown Item component OnClickEvent returns the label string property and does not match the current IX Core functionality
GitHub Issue Number: #78 
With the changes, the Dropdown Item component OnClickEvent returns the DropdownItem component itself allowing access to more properties and matches the functionality of the IX Core.
-
-
=> Resolve Issue 78 : DropdownItem Click Event Parameter Type Issue

README.md, SiemensIXBlazor/Components/About/AboutMenu.razor.cs, SiemensIXBlazor/Components/Application/Application.razor.cs, SiemensIXBlazor/Components/CategoryFilter/CategoryFilter.razor.cs, SiemensIXBlazor/Components/DateDropdown/DateDropdown.razor.cs, SiemensIXBlazor/Components/MenuSettings/MenuSettings.razor.cs, SiemensIXBlazor/Components/Tree/Tree.razor.cs, SiemensIXBlazor/Interops/BaseInterop.cs, SiemensIXBlazor/Interops/FileUploadInterop.cs, SiemensIXBlazor/Interops/TabsInterop.cs
Aligned path in interpose to new PackageId.
=> fix interop path to new PackageId.

README.md, SiemensIXBlazor.Tests/Dropdown/DropdownTest.cs, SiemensIXBlazor/Components/Dropdown/Dropdown.razor, SiemensIXBlazor/Components/Dropdown/Dropdown.razor.cs
There is no implementation of Group with Context
Group with context has been implemented
if you add **IsForGroupContext** parameter to **Dropdown** under **Group** then you can see the context menu
In screenshots below you can see that you should add **IsForGroupContext** to **Dropdown**
The Unit Test Results
-
- [x ] 🦮 Accessibility (a11y) features were implemented
- [x ] 🗺️ Internationalization (i18n) - no hard coded strings
- [x ] 📲 Responsiveness - components handle viewport changes and content overflow gracefully
- [ x] 📄 Documentation was reviewed/updated
- [ x] 🧪 Unit tests were added/updated and pass (`dotnet test`)
- [ x] 🏗️ Successful compilation (`dotnet …
=> Group with Context menu implemented

README.md, SiemensIXBlazor.Tests/TypographyTest.cs, SiemensIXBlazor/Components/Typography/Typography.razor, SiemensIXBlazor/Components/Typography/Typography.razor.cs, SiemensIXBlazor/Enums/Typography/TextDecoration.cs, SiemensIXBlazor/Enums/Typography/TypographyColor.cs, SiemensIXBlazor/Enums/Typography/TypographyFormat.cs
The Typography component is not implemented, it is only available as a JavaScipt component.
- Typography can be used as a Blazor component.
> ![image](https://github.com/user-attachments/assets/2deea8a1-278d-4683-a715-7bf6c6771b11)
> ![image](https://github.com/user-attachments/assets/857aedf4-1fd8-4b78-9d46-a86efdccf9a5)
=> Typography Component Implementation

SiemensIXBlazor.Tests/TooltipTest.cs, SiemensIXBlazor/Components/Tooltip/Tooltip.Razor.cs, SiemensIXBlazor/Components/Tooltip/Tooltip.razor, SiemensIXBlazor/Enums/Tooltip/TooltipVariant.cs
- Tooltip component was missing.
GitHub Issue Number: NA
- Tooltip component is added.
- Tooltip enum is added.
=> Tooltip component and enum added

README.md, SiemensIXBlazor/SiemensIXBlazor.csproj
Although the current version of the validation tooltip component example was available in the README, the old version is still present as well.
- The old validation tooltip section has been removed from README.
=> Readme updated

SiemensIXBlazor.Tests/CardListTests.cs, SiemensIXBlazor.Tests/CategoryFilterTests.cs, SiemensIXBlazor.Tests/DateDropdownTest.cs, SiemensIXBlazor.Tests/Menu/MenuItemTest.cs, SiemensIXBlazor.Tests/Menu/MenuTest.cs, SiemensIXBlazor.Tests/SplitButton/SplitButtonTest.cs, SiemensIXBlazor/Components/CardList/CardList.razor, SiemensIXBlazor/Components/CardList/CardList.razor.cs, SiemensIXBlazor/Components/CategoryFilter/CategoryFilter.razor, SiemensIXBlazor/Components/CategoryFilter/CategoryFilter.razor.cs, SiemensIXBlazor/Components/DateDropdown/DateDropdown.razor, SiemensIXBlazor/Components/DateDropdown/DateDropdown.razor.cs, SiemensIXBlazor/Components/Menu/Menu.razor, SiemensIXBlazor/Components/Menu/Menu.razor.cs, SiemensIXBlazor/Components/Menu/MenuItem.razor, SiemensIXBlazor/Components/Menu/MenuItem.razor.cs, SiemensIXBlazor/Components/SplitButton/SplitButton.razor, SiemensIXBlazor/Components/SplitButton/SplitButton.razor.cs, SiemensIXBlazor/Enums/Button/ButtonVariant.cs, SiemensIXBlazor/Enums/Button/SplitButtonCloseBehavior.cs
Some components did not have features added until ix@2.5.0 since ix@2.2.0, for example:
- Menu component - Pinned property
- MenuItem component - Label property
- Button component - Danger variant
- SplitButton component - Close behavior
- DateDropdown component - Disabled property
- CardList component - HideShowAll property
- CategoryFilter component - Disabled and Readonly properties
Components are updated with new properties and variants along with unit tests. (version ix@2.5.0)
=> Update version diffs

SiemensIXBlazor.Tests/DateDropdownTest.cs, SiemensIXBlazor.Tests/Select/SelectItemTest.cs, SiemensIXBlazor.Tests/Select/SelectTest.cs, SiemensIXBlazor/Components/DateDropdown/DateDropdown.razor, SiemensIXBlazor/Components/DateDropdown/DateDropdown.razor.cs, SiemensIXBlazor/Components/Select/Select.razor, SiemensIXBlazor/Components/Select/Select.razor.cs
- The `DateDropdown` component does not support specifying the starting day of the week (`WeekStartIndex`) or localization settings (`Locale`), which were introduced in the latest IX version.
- The `Select` component lacks several properties, and in the latest version of IX, it is a form-ready component.
- `Select` and `SelectItem` components lack tests.
- Added new properties to `DateDropdown`:
- `WeekStartIndex`
- `Locale`
- Added new properties to `Select` component:
- `Name`
- `Required`
- `ShowTextAsTooltip`
- `InfoText`
- `InvalidText`
- `Label`
- `ValidText`
- `WarningText`
- `HelperText`
- `DropdownWidth`
- `DropdownMaxWidth`
- Added `ixBlur` event support to `Select` component
- Added tests for `Select` and `SelectItem`
A pull request can only be merged if all of these conditions …
=> Add New Properties to Select and DateDropdown Components

SiemensIXBlazor.Tests/DateDropdownTest.cs, SiemensIXBlazor.Tests/ExpandingSearchTest.cs, SiemensIXBlazor/Components/DateDropdown/DateDropdown.razor, SiemensIXBlazor/Components/DateDropdown/DateDropdown.razor.cs, SiemensIXBlazor/Components/ExpandingSearch/ExpandingSearch.razor, SiemensIXBlazor/Components/ExpandingSearch/ExpandingSearch.razor.cs, SiemensIXBlazor/Enums/DateDropdown/DateDropdownVariant.cs, SiemensIXBlazor/Enums/ExpandingSearch/ExpandingSearchVariant.cs
The `DateDropdown` and `ExpandingSearch` components do not support the properties introduced in IX version 2.7.0.
To align with IX version 2.7.0, the following properties have been added:
- **DateDropdown**:
- `Outline`
- `Ghost`
- `Loading`
- `Variant`
- **ExpandingSearch**:
- `Outline`
- `Ghost`
- `Variant`
- `FullWidth`
=> Add New Properties to DateDropdown and ExpandingSearch

README.md, SiemensIXBlazor.Tests/ChipTests.cs, SiemensIXBlazor.Tests/EventList/EventListItemTest.cs, SiemensIXBlazor.Tests/PillTest.cs, SiemensIXBlazor/Components/Chip/Chip.razor, SiemensIXBlazor/Components/Chip/Chip.razor.cs, SiemensIXBlazor/Components/EventList/EventListItem.razor, SiemensIXBlazor/Components/EventList/EventListItem.razor.cs, SiemensIXBlazor/Components/Pill/Pill.razor, SiemensIXBlazor/Components/Pill/Pill.razor.cs
The color prop is currently used across multiple components (ix-chip, ix-event-list, and ix-pill), but the naming does not follow the new naming conventions. Corresponding unit tests also rely on the old prop names.
- Renamed color props to follow the new naming convention:
- ix-chip: color → chip-color
- ix-event-list: color → item-color
- ix-pill: color → pill-color
- Updated corresponding component tests to use the new prop names
=> Refactor color properties

README.md, SiemensIXBlazor.Tests/ActionCardTests.cs, SiemensIXBlazor.Tests/CardTests.cs, SiemensIXBlazor.Tests/Helper/EnumParserTests.cs, SiemensIXBlazor.Tests/PushCardTest.cs, SiemensIXBlazor/Components/ActionCard/ActionCard.razor.cs, SiemensIXBlazor/Components/Card/Card.razor.cs, SiemensIXBlazor/Components/PushCard/PushCard.razor.cs, SiemensIXBlazor/Enums/Card/CardVariant.cs, SiemensIXBlazor/Enums/PushCard/PushCardVariant.cs
The insight and notification variants are currently used in ix-action-card, ix-card, and ix-push-card components. These variants have been removed in ix v3.0.0 and are no longer supported.
- Replaced deprecated insight and notification variants with the new outline and filled variants in:
- ix-action-card
- ix-card
- ix-push-card
- Updated corresponding component tests to use the new variant values
- Updated README examples to reflect these changes
=> Refactor card variants

SiemensIXBlazor/Components/Tabs/Tabs.razor.cs, SiemensIXBlazor/Interops/TabsInterop.cs
The InitialComponent method in the interop layer was causing runtime errors on the JavaScript side when invoked. 
- Removed usage of the InitialComponent interop method from the component to resolve JS runtime errors.
=> fix: remove InitialComponent interop

README.md, SiemensIXBlazor.Tests/ChipTests.cs, SiemensIXBlazor.Tests/PillTest.cs, SiemensIXBlazor/Components/Chip/Chip.razor, SiemensIXBlazor/Components/Chip/Chip.razor.cs, SiemensIXBlazor/Components/Pill/Pill.razor, SiemensIXBlazor/Components/Pill/Pill.razor.cs
- Currently, the `Chip` and `Pill` components do not support displaying tooltip text.
- Added a `TooltipText` parameter to `Chip` and `Pill` components to support optional hover tooltips.
- Implemented unit tests to verify correct rendering and behavior of the tooltip text.
=> feat: add TooltipText support and tests for Chip and Pill components

README.md, SiemensIXBlazor/Enums/MessageBar/MessageBarType.cs
- The `MessageBar` component still includes the deprecated `danger` message type without a deprecation notice.
- Documentation example currently uses the deprecated `danger` type.
- Added new message types to `MessageBar`.
- Marked the `danger` type as deprecated.
- Updated documentation example to use `info` instead of `danger`.
=> feat(MessageBar): add new types and deprecate danger

SiemensIXBlazor.Tests/Menu/MenuTest.cs
Wrong component type is used in Menu Test
Replaced with Correct Component Type 
-
-
- [x ] 🧪 Unit tests were added/updated and pass (`dotnet test`)
=> Fix : Remove Wrong Component Type in MenuTest
