- SiemensIXBlazor/Components/EventList/EventListItem.razor.cs
Just a small typo fix I found while using the library. Sorry for the PR, but otherwise my colleagues will wonder, why my last commit throws an error.
> Fixed typo

- SiemensIXBlazor/Components/AGGrid/AGGrid.razor.cs
- SiemensIXBlazor/Components/AGGrid/ColumnDefs.cs
- SiemensIXBlazor/Components/Drawer/Drawer.razor
- SiemensIXBlazor/SiemensIXBlazor_NpmJS/src/index.js
OnCellClicked eventcallback
GetSelectedRows
new column properties:
- Hide
- LockPosition
- SuppressMovable
> Extend AGGrid

- SiemensIXBlazor/Components/DatePicker/DatePicker.razor
- SiemensIXBlazor/Components/DatePicker/DatePicker.razor.cs
Locale and I18nDone props are added.
Default value of From prop is removed.
EventDelimiter and TextSelectDate props are removed.
DateChange event is added.
> DatePicker update issue #37

- SiemensIXBlazor/Components/Pane/Pane.razor
- SiemensIXBlazor/Components/Pane/Pane.razor.cs
- SiemensIXBlazor/Components/PaneLayout/PaneLayout.razor
- SiemensIXBlazor/Components/PaneLayout/PaneLayout.razor.cs
- SiemensIXBlazor/Enums/Pane/PaneComposition.cs
- SiemensIXBlazor/Enums/Pane/PaneVariant.cs
- SiemensIXBlazor/Objects/Pane/PaneBorderlessChangedEventResponse.cs
- SiemensIXBlazor/Objects/Pane/PaneExpandedChangedEventResponse.cs
- SiemensIXBlazor/Objects/Pane/PaneVariantChangedEventResponse.cs
**Pane Layout**
**Pane Expanded**
> Issue#35 : Implement Panes Component

- README.md
> Issue#35: Readme Updated for Pane and PaneLayout

- .github/PULL_REQUEST_TEMPLATE
- SUPPORT.md
> Support file and PR template added.

- .github/dependabot.yml
We have to trace dependencies'' versions manually.
GitHub Issue Number: #51 
Now, we can set CRON job for dependabot to trace our dependency versions automatically. 
> chore: Add Dependabot configuration file

- .github/dependabot.yml
We have to trace dependencies'' versions manually.
GitHub Issue Number: #51 
Now, we can set CRON job for dependabot to trace our dependency versions automatically.
-
-
> chore: Update package-ecosystem value in Dependabot configuration file

- SiemensIXBlazor.Tests/DateDropdownTest.cs
- SiemensIXBlazor.Tests/DatePickerTest.cs
- SiemensIXBlazor.Tests/DateTimePickerTest.cs
- SiemensIXBlazor.Tests/DividerTest.cs
- SiemensIXBlazor.Tests/DrawerTest.cs
- SiemensIXBlazor.Tests/Dropdown/DropdownItemTest.cs
- SiemensIXBlazor.Tests/Dropdown/DropdownTest.cs
- SiemensIXBlazor.Tests/DropdownButtonTest.cs
- SiemensIXBlazor.Tests/EChartsTest.cs
- SiemensIXBlazor.Tests/EmptyStateTest.cs
- SiemensIXBlazor.Tests/EventList/EventListItemTest.cs
- SiemensIXBlazor.Tests/EventList/EventListTest.cs
- SiemensIXBlazor.Tests/ExpandingSearchTest.cs
- SiemensIXBlazor.Tests/Flip/FlipTileContentTest.cs
- SiemensIXBlazor.Tests/Flip/FlipTileTest.cs
- SiemensIXBlazor.Tests/Group/GroupItemTest.cs
- SiemensIXBlazor.Tests/Group/GroupTest.cs
- SiemensIXBlazor.Tests/KPITest.cs
- SiemensIXBlazor.Tests/KeyValueListTest.cs
- SiemensIXBlazor.Tests/KeyValueTest.cs
- SiemensIXBlazor.Tests/LayoutGrid/ColTest.cs
- SiemensIXBlazor.Tests/LayoutGrid/LayoutGridTest.cs
- SiemensIXBlazor.Tests/LayoutGrid/RowTest.cs
- SiemensIXBlazor.Tests/LinkButtonTest.cs
- SiemensIXBlazor.Tests/MapNavigationTest.cs
- SiemensIXBlazor.sln
- SiemensIXBlazor.sln.licenseheader
- SiemensIXBlazor/Components/DatePicker/DatePicker.razor.cs
- SiemensIXBlazor/Components/DateTimePicker/DateTimePicker.razor.cs
- SiemensIXBlazor/Components/Group/GroupItem.razor.cs
Component unit tests are missing.
GitHub Issue Number: #46 
I added unit tests for components [DateDropdown-MapNavigation]
> Adding component unit tests [DateDropdown-MapNavigation]

- README.md
- SECURITY.md
Readme and security files are not up to date.
GitHub Issue Number: #46 
Readme an security files are updated. 
> Readme and security updates

- SiemensIXBlazor/SiemensIXBlazor.csproj
- docs/SiemensIXBlazor__0.5.0__ReadMe_OSS.html
The repo doesn't have any readme_oss file
GitHub Issue Number: #73
The repo has "ReadMe_OSS" file
> docs: Siemens ReadMeOSS added in repo

- README.md
- SiemensIXBlazor.Tests/MapNavigation/MapNavigationOverlayTest.cs
- SiemensIXBlazor.Tests/MapNavigation/MapNavigationTest.cs
- SiemensIXBlazor/Components/MapNavigationOverlay/MapNavigationOverlay.razor
- SiemensIXBlazor/Components/MapNavigationOverlay/MapNavigationOverlay.razor.cs
Map Navigation Overlay Component does not exist.
Map Navigation Overlay Component implemented.
- Map Navigation Overlay Component Added
- Tests Added
- Test Results checked
Component :
Test Result:
- [x ] 📄 Documentation was reviewed/updated
- [ x] 🧪 Unit tests were added/updated and pass (`dotnet test`)
- [ x] 🏗️ Successful compilation (`dotnet build`, changes pushed)
> Map Navigation Overlay Component Implemented

- SiemensIXBlazor/Components/Application/Application.razor.cs
- SiemensIXBlazor/Components/CategoryFilter/CategoryFilter.razor.cs
- SiemensIXBlazor/Components/DateDropdown/DateDropdown.razor.cs
- SiemensIXBlazor/Components/MenuAbout/MenuAbout.razor.cs
- SiemensIXBlazor/Components/MenuSettings/MenuSettings.razor.cs
- SiemensIXBlazor/Components/Tree/Tree.razor.cs
Interop path was wrong, some components was not working
interop paths corrected
-
-
> Fix : Interop path corrected

- README.md
- SiemensIXBlazor.Tests/Dropdown/DropdownHeaderTests.cs
- SiemensIXBlazor/Components/Dropdown/DropdownHeader.razor
- SiemensIXBlazor/Components/Dropdown/DropdownHeader.razor.cs
- SiemensIXBlazor/SiemensIXBlazor.csproj
- SiemensIXBlazor/SiemensIXBlazor_NpmJS/package-lock.json
- SiemensIXBlazor/SiemensIXBlazor_NpmJS/package.json
- scripts/pre-build.bat
Missing component: Dropdown Header
Component Added: Dropdown Header
> Dropdown Header Component Added

- .gitignore
- SiemensIXBlazor.sln
- SiemensIXBlazor/Components/CategoryFilter/CategoryFilter.razor.cs
- SiemensIXBlazor/Enums/CategoryFilter/LogicalFilterEnumExtension.cs
- SiemensIXBlazor/Enums/CategoryFilter/LogicalFiterOperator.cs
- SiemensIXBlazor/SiemensIXBlazor.csproj
- SiemensIXBlazor/wwwroot/js/siemens-ix/interops/categoryFilterInterop.js
Logical Filter optional attribute implemented
- [ x] 🗺️ Internationalization (i18n) - no hard coded strings
- [x ] 🏗️ Successful compilation (`dotnet build`, changes pushed)
> IX: Implement optional filter logic

- SiemensIXBlazor.Tests/Menu/MenuTest.cs
- SiemensIXBlazor/Components/Menu/Menu.razor.cs
Menu does not contains OpenSettings and Open AboutEvent
Menu does not contains OpenSettings and Open AboutEvent
-
-
- [x ] 🧪 Unit tests were added/updated and pass (`dotnet test`)
- [ x] 🏗️ Successful compilation (`dotnet build`, changes pushed)
> Update : Events added for Menu , Tests updated

- SiemensIXBlazor.Tests/Flip/FlipTileTest.cs
- SiemensIXBlazor/Components/Flip/FlipTile.razor
- SiemensIXBlazor/Components/Flip/FlipTile.razor.cs
Flip Tile does not contain ToggleEvent
Flip Tile contains Toggle Event
-
-
- [ x] 🧪 Unit tests were added/updated and pass (`dotnet test`)
- [ x] 🏗️ Successful compilation (`dotnet build`, changes pushed)
> Update : Toggle Event Added for Flip Tile

- SiemensIXBlazor.Playground/Components/App.razor
- SiemensIXBlazor.Playground/Components/Pages/InputFieldsAndSelections/CategoryFilter/CategoryFilter.razor
- SiemensIXBlazor.Playground/Components/Pages/InputFieldsAndSelections/CategoryFilter/CategoryFilter.razor.cs
- SiemensIXBlazor.Playground/Components/Pages/InputFieldsAndSelections/Checkbox/Checkbox.razor
- SiemensIXBlazor.Playground/Components/Pages/InputFieldsAndSelections/DateDropdown/DateDropdown.razor
- SiemensIXBlazor.Playground/Components/Pages/InputFieldsAndSelections/DateDropdown/DateDropdown.razor.cs
- SiemensIXBlazor.Playground/Components/Pages/InputFieldsAndSelections/Upload/Upload.razor
- SiemensIXBlazor.Playground/Components/Pages/InputFieldsAndSelections/Upload/Upload.razor.cs
- SiemensIXBlazor.Playground/Interops/PrismInterop.cs
- SiemensIXBlazor.Playground/Program.cs
- SiemensIXBlazor.Playground/Services/CodeHighlightService .cs
- SiemensIXBlazor.Playground/Services/ICodeHighlightService.cs
- SiemensIXBlazor.Playground/Shared/CodeHighlighter/CodeHiglighter.razor
- SiemensIXBlazor.Playground/Shared/CodeHighlighter/CodeHiglighter.razor.cs
- SiemensIXBlazor.Playground/Shared/CodeHighlighter/CodeHiglighter.razor.css
- SiemensIXBlazor.Playground/Shared/PlaygroundBase/PlaygroundBase.razor
- SiemensIXBlazor.Playground/Shared/PlaygroundBase/PlaygroundBase.razor.cs
- SiemensIXBlazor.Playground/wwwroot/app.css
- Prism Code Highlighter Service  added 
- Base Component Added to improve Reusability
- Upload , CategoryFilter , DateDropdown Component implemented for Playground
> Add Prism Integration and PlaygroundBase Component

- SiemensIXBlazor.Playground/Components/Pages/ButtonsAndActions/Button/Button.razor
- SiemensIXBlazor.Playground/Components/Pages/ButtonsAndActions/Button/Button.razor.cs
- SiemensIXBlazor.Playground/Components/Pages/ButtonsAndActions/DropdownButton/DropdownButton.razor
- SiemensIXBlazor.Playground/Components/Pages/ButtonsAndActions/DropdownButton/DropdownButton.razor.cs
- SiemensIXBlazor.Playground/Components/Pages/ButtonsAndActions/IconButton/IconButton.razor
- SiemensIXBlazor.Playground/Components/Pages/ButtonsAndActions/IconButton/IconButton.razor.cs
- SiemensIXBlazor.Playground/Components/Pages/ButtonsAndActions/LinkButton/LinkButton.razor
- SiemensIXBlazor.Playground/Components/Pages/ButtonsAndActions/LinkButton/LinkButton.razor.cs
- SiemensIXBlazor.Playground/Components/Pages/ButtonsAndActions/SplitButton/SplitButton.razor
- SiemensIXBlazor.Playground/Components/Pages/ButtonsAndActions/SplitButton/SplitButton.razor.cs
- SiemensIXBlazor.Playground/Components/Pages/ButtonsAndActions/ToggleButton/ToggleButton.razor
- SiemensIXBlazor.Playground/Components/Pages/ButtonsAndActions/ToggleButton/ToggleButton.razor.cs
- SiemensIXBlazor.Playground/Components/Pages/InputFieldsAndSelections/Slider/Slider.razor
- SiemensIXBlazor.Playground/Components/Pages/InputFieldsAndSelections/Slider/Slider.razor.cs
- SiemensIXBlazor.Playground/Components/Pages/InputFieldsAndSelections/Toggle/Toggle.razor
- SiemensIXBlazor.Playground/Components/Pages/InputFieldsAndSelections/Toggle/Toggle.razor.cs
Playground components for ButtonsAndActions are missing
Playground components for ButtonsAndActions has been developed
-
-
> Add Playground components for ButtonsAndActions

- SiemensIXBlazor.Playground/Components/Pages/SystemFeedbackAndStatus/Chip/Chip.razor
- SiemensIXBlazor.Playground/Components/Pages/SystemFeedbackAndStatus/Chip/Chip.razor.cs
- SiemensIXBlazor.Playground/Components/Pages/SystemFeedbackAndStatus/Chip/Chip.razor.css
- SiemensIXBlazor.Playground/Components/Pages/SystemFeedbackAndStatus/EmptyState/EmptyState.razor
- SiemensIXBlazor.Playground/Components/Pages/SystemFeedbackAndStatus/EmptyState/EmptyState.razor.cs
- SiemensIXBlazor.Playground/Components/Pages/SystemFeedbackAndStatus/MessageBar/MessageBar.razor
- SiemensIXBlazor.Playground/Components/Pages/SystemFeedbackAndStatus/MessageBar/MessageBar.razor.cs
- SiemensIXBlazor.Playground/Components/Pages/SystemFeedbackAndStatus/MessageBar/MessageBar.razor.css
- SiemensIXBlazor.Playground/Components/Pages/SystemFeedbackAndStatus/MessageBar/Types/MessageBarType.razor
- SiemensIXBlazor.Playground/Components/Pages/SystemFeedbackAndStatus/MessageBar/Types/MessageBarType.razor.cs
- SiemensIXBlazor.Playground/Components/Pages/SystemFeedbackAndStatus/MessageBar/Types/MessageBarType.razor.css
- SiemensIXBlazor.Playground/Components/Pages/SystemFeedbackAndStatus/Pill/Pill.razor
- SiemensIXBlazor.Playground/Components/Pages/SystemFeedbackAndStatus/Pill/Pill.razor.cs
- SiemensIXBlazor.Playground/Components/Pages/SystemFeedbackAndStatus/Pill/Pill.razor.css
- SiemensIXBlazor.Playground/Components/Pages/SystemFeedbackAndStatus/Spinner/Spinner.razor
- SiemensIXBlazor.Playground/Components/Pages/SystemFeedbackAndStatus/Spinner/Spinner.razor.cs
- SiemensIXBlazor.Playground/Components/Pages/SystemFeedbackAndStatus/Toast/Toast.razor
- SiemensIXBlazor.Playground/Components/Pages/SystemFeedbackAndStatus/Toast/Toast.razor.cs
- SiemensIXBlazor.Playground/Components/Pages/SystemFeedbackAndStatus/Tooltip/Tooltip.razor
- SiemensIXBlazor.Playground/Components/Pages/SystemFeedbackAndStatus/Tooltip/Tooltip.razor.cs
- SiemensIXBlazor.Playground/Components/Pages/SystemFeedbackAndStatus/Tooltip/Tooltip.razor.css
Playground System feedback and status component are missing.
-  Playground System feedback and status component implemented.
> Add: Playground System feedback and status component

- SiemensIXBlazor/Components/Checkbox/Checkbox.razor
- SiemensIXBlazor/Components/Checkbox/Checkbox.razor.cs
- SiemensIXBlazor/Components/Checkbox/CheckboxGroup.razor
- SiemensIXBlazor/Components/Checkbox/CheckboxGroup.razor.cs
- SiemensIXBlazor/Components/CustomField/CustomField.razor
- SiemensIXBlazor/Components/CustomField/CustomField.razor.cs
- SiemensIXBlazor/Components/DateInput/DateInput.razor
- SiemensIXBlazor/Components/DateInput/DateInput.razor.cs
- SiemensIXBlazor/Components/Input/Input.razor
- SiemensIXBlazor/Components/Input/Input.razor.cs
- SiemensIXBlazor/Components/NumberInput/NumberInput.razor
- SiemensIXBlazor/Components/NumberInput/NumberInput.razor.cs
- SiemensIXBlazor/Components/Radio/Radio.razor
- SiemensIXBlazor/Components/Radio/Radio.razor.cs
- SiemensIXBlazor/Components/Radio/RadioGroup.razor
- SiemensIXBlazor/Components/Radio/RadioGroup.razor.cs
- SiemensIXBlazor/Components/TextArea/TextArea.razor
- SiemensIXBlazor/Components/TextArea/TextArea.razor.cs
- SiemensIXBlazor/Components/TimeInput/TimeInput.razor
- SiemensIXBlazor/Components/TimeInput/TimeInput.razor.cs
- SiemensIXBlazor/wwwroot/js/siemens-ix/interops/checkboxInterop.js
The project is missing the following form input components: custom field, checkbox, date input, input, number input, radio, text area and time input.
Custom field, checkbox, date input, input, number input, radio, text area, and time input components are added. This project now supports those components. 
-
-
> Add Input Components
